---
# https://twitter.com/mattifestation/status/1063145928696258562
# https://gist.github.com/mattifestation/dfdd41e5020f4286e9b6486545abc359

- name: Check if AMSI logging marker
  win_stat:
    path: c:\Windows\system32\Logs\MyAMSILogger.txt
  register: amsi

- name: Enable AMSI logging
  win_shell: "{{ item }}"
  with_items:
    - New-AutologgerConfig -Name 'MyAMSILogger' -Guid "{$((New-Guid).Guid)}" -Start Enabled
    - Add-EtwTraceProvider -AutologgerName 'MyAMSILogger' -Guid '{2A576B87-09A7-520E-C21A-4942F0271D67}' -Level 0xff -MatchAnyKeyword 0x80000000000001 -Property 0x41
  when: not amsi.stat.exists

- name: Set AMSI logging marker
  win_file:
    path: c:\Windows\system32\Logs\MyAMSILogger.txt
    state: touch
  when: not amsi.stat.exists
