---

# Review evt/log files to 100-500M + corresponding GPO
# https://dfirblog.wordpress.com/2015/10/11/protecting-windows-networks-essential-logging/
# https://logrhythm.com/fr/blog/powershell-command-line-logging/
# https://malwarearchaeology.squarespace.com/cheat-sheets/
# https://support.microsoft.com/en-us/kb/957662
# https://technet.microsoft.com/en-us/library/cc748849.aspx
# http://lifeofageekadmin.com/changing-windows-20032008-eventlog-size/
## https://msdn.microsoft.com/en-us/library/windows/desktop/aa363648(v=vs.85).aspx
## https://support.microsoft.com/en-ca/kb/957662
## alternative:     wevtutil sl <LogName> /ms:<MaxSizeInBytes>
## PS C:\> get-eventlog -list

- name: Debug | win_eventlog_maxsize
  ansible.builtin.debug:
    var: win_eventlog_maxsize

- name: Base Event Log size review
  ansible.windows.win_regedit:
    key: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item }}"
    value: MaxSize
    datatype: dword
    data: "{{ win_eventlog_maxsize }}"
  with_items:
    - Application
    - Security
    - System
    - Setup
    - Windows PowerShell

- name: Base Event Log retention review
  ansible.windows.win_regedit:
    key: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item }}"
    value: Retention
    datatype: dword
    data: "{{ win_eventlog_retention }}"
  with_items:
    - Application
    - Security
    - System
    - Setup
    - Windows PowerShell

- name: WINEVT Channels Event Log Enabled
  ansible.windows.win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: Enabled
    datatype: dword
    data: 1
  with_items: "{{ win_eventlog_channels }}"

- name: WINEVT Channels Event Log size review
  ansible.windows.win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: MaxSize
    datatype: dword
    data: "{{ win_eventlog_maxsize }}"
  with_items: "{{ win_eventlog_channels }}"

- name: WINEVT Channels Event Log retention review
  ansible.windows.win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: Retention
    datatype: dword
    data: "{{ win_eventlog_retention }}"
  with_items: "{{ win_eventlog_channels }}"

- name: Check Logs channel registry entries
  ansible.windows.win_reg_stat:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
  with_items: "{{ win_eventlog_channels }}"
  register: logreg
- name: Debug | logreg
  ansible.builtin.debug:
    var: logreg
